    services:
        db:
            image: postgres:15
            restart: always
            environment:
                POSTGRES_DB: todolist
                POSTGRES_USER: postgres
                POSTGRES_PASSWORD: password
            ports:
                - "5432:5432"
            volumes:
                - db_data:/var/lib/postgresql/data

        web:
            build: .
            ports:
                - "5000:5000"
            depends_on:
                - db
            environment:
                - DB_HOST=db
                - DB_NAME=todolist
                - DB_USER=postgres
                - DB_PASSWORD=password

    volumes:
        db_data:
